<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>系统配置</title>
	<link rel="stylesheet" type="text/css" href="/public/zui/dist/css/zui.min.css">
	<script type="text/javascript" src="/public/zui/dist/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="/public/zui/dist/js/zui.min.js"></script>
</head>
<body>
<div class="panel panel-successcvcv" style="padding-top:37px;">
	<div class="panel-heading navbar-fixed-top" style="background:#ddf4df;">
		<span class="col-sm-1">系统配置</span>
	</div>
	<div class="panel-body">
		<ul class="nav nav-tabs">
			<li class="active"><a data-tab href="#tabContent1">站点信息</a></li>
			<li><a data-tab href="#tabContent2">邮件服务</a></li>
			<li><a data-tab href="#tabContent3">微信公众号</a></li>
			<li><a data-tab href="#tabContent4">微信商户平台</a></li>
			<li><a data-tab href="#tabContent5">微信开放平台</a></li>
			<li><a data-tab href="#tabContent6">微信小程序</a></li>
			<li><a data-tab href="#tabContent7">阿里云OSS</a></li>
			<li><a data-tab href="#tabContent8">阿里云短信</a></li>
		</ul>
		<form method="post" class="form-horizontal">
			<div class="tab-content" style="margin-top: 30px;">
				<div class="tab-pane active" id="tabContent1">
					<div class="form-group">
						<label class="col-sm-1">标题</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="title" value="<?php echo $system['title']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-1">关键词</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="keyword" value="<?php echo $system['keyword']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-1">描述</label>
						<div class="col-sm-10">
							<textarea name="description" class="form-control kindeditor"><?php echo $system['description']; ?></textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-1">版权</label>
						<div class="col-sm-10">
							<textarea name="copyfrom" class="form-control kindeditor"><?php echo $system['copyfrom']; ?></textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-1">备注</label>
						<div class="col-sm-10">
							<textarea name="remark" class="form-control kindeditor"><?php echo $system['remark']; ?></textarea>
						</div>
					</div>
				</div>

				<div class="tab-pane" id="tabContent2">
					<div class="form-group">
						<label class="col-sm-2">SMTP服务器</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="smtp_server" value="<?php echo $system['smtp_server']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">SMTP服务器端口</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="smtp_port" value="<?php echo $system['smtp_port']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">SMTP服务器邮箱</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="smtp_email" value="<?php echo $system['smtp_email']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">SMTP服务器帐号</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="smtp_user" value="<?php echo $system['smtp_user']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">SMTP服务器密码</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="smtp_password" value="<?php echo $system['smtp_password']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">SMTP身份验证</label>
						<div class="col-sm-6">
							<?php if($system['smtp_auth'] == 1){ ?>
							<label class="radio-inline"><input type="radio" name="smtp_auth" value="1" checked> 是 </label>
							<label class="radio-inline"><input type="radio" name="smtp_auth" value="0"> 否 </label>
							<?php }else{ ?>
							<label class="radio-inline"><input type="radio" name="smtp_auth" value="1"> 是 </label>
							<label class="radio-inline"><input type="radio" name="smtp_auth" value="0" checked> 否 </label>
							<?php } ?>
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent3">
					<div class="form-group">
						<label class="col-sm-2">公众号appid</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="wchat_appid" value="<?php echo $system['wchat_appid']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">公众号secret</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="wchat_secret" value="<?php echo $system['wchat_secret']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">公众号token</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="wchat_token" value="<?php echo $system['wchat_token']; ?>">
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent4">
					<div class="form-group">
						<label class="col-sm-2">微信支付商户号</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="wchat_cmchid" value="<?php echo $system['wchat_cmchid']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">微信支付签名串</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="wchat_signKey" value="<?php echo $system['wchat_signKey']; ?>">
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent5">
					<div class="form-group">
						<label class="col-sm-2">开放平台AppID</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="open_AppID" value="<?php echo $system['open_AppID']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">开放平台AppSecret</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="open_AppSecret" value="<?php echo $system['open_AppSecret']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">开放平台Token</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="open_Token" value="<?php echo $system['open_Token']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">开放平台AesKey</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="open_AesKey" value="<?php echo $system['open_AesKey']; ?>">
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent6">
					<div class="form-group">
						<label class="col-sm-2">appid</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="miniprogram_appid" value="<?php echo $system['miniprogram_appid']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">secret</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="miniprogram_secret" value="<?php echo $system['miniprogram_secret']; ?>">
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent7">
					<div class="form-group">
						<label class="col-sm-2">AccessKeyID</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_AccessKeyID" value="<?php echo $system['oss_AccessKeyID']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">AccessKey</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_AccessKey" value="<?php echo $system['oss_AccessKey']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">endPoint（地域节点）</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_endPoint" value="<?php echo $system['oss_endPoint']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">Bucket（存储）</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_bucket" value="<?php echo $system['oss_bucket']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">Bucket（域名）</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_bucket_host" value="<?php echo $system['oss_bucket_host']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">callback（回调地址）</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="oss_callback" value="<?php echo $system['oss_callback']; ?>">
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tabContent8">
					<div class="form-group">
						<label class="col-sm-2">AccessKeyID</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="sms_AccessKeyID" value="<?php echo $system['sms_AccessKeyID']; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2">AccessKey</label>
						<div class="col-sm-6">
							<input type="text" class="form-control" name="sms_AccessKey" value="<?php echo $system['sms_AccessKey']; ?>">
						</div>
					</div>
				</div>
			</div>
		</form>
		<div class="container" style="margin-top: 50px;">
			<button id="submit" class="btn btn-primary ">提交</button>
		</div>
	</div>
</div>
<script type="text/javascript">
	//修改系统配置
	$("#submit").click(function(){
		var dataForm = $("form").serialize();
		$.ajax({
			type:"post",
			url:"setting",
			data:dataForm,
			success:function(result){
				if (result.code == -1) {
					window.top.relogin();
				} else if (result.code == 1) {
					new $.zui.Messager('编辑成功！', {type:'success', icon:'ok-sign'}).show();
				} else {
					new $.zui.Messager(result.msg, {type:'danger', icon:'exclamation-sign'}).show();
				}
			}
		});
	});
</script>
</body>
</html>